### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by amoghakancharla**
I've added more concise statements and fixed few grammatical errors.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@amoghak-ds thank you this is awesome, I'll review and merge shortly.

**Comment by amoghakancharla** [comment]
Sure! @mrinalwadhwa

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
@amoghak-ds Thank you for spending time on this, before we can merge please

- [x] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by mrinalwadhwa** [comment]
@amoghak-ds thank you for an awesome first contribution!

Please let us know if your have any questions as you explore other parts of our codebase and documentation. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Pull request merged**
